<?php

namespace LibraryBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{

  public function findByIsDeleted() {
      $qb = $this->createQueryBuilder('s');

      echo( $qb->getQuery()->getSQL() );

      //$qb->getQuery()->getResult();
      
      return $qb;
  }

}
